set1 = set()
str1 = input('Please insert String1 : ')
str2 = input('Please insert String2 : ')
str3 = input('Please insert String3 : ')
set1.add(str1)
set1.add(str2)
set1.add(str3)
print(set1)

set2 = set()
set2.update({str1, str2, str3})
print(set2)
